/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jogoprincipal;

import java.util.Random;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author Manoel
 */
public class ContraMaq extends javax.swing.JPanel implements Escolha{

    /**
     * Creates new form ContraMaq
     */
    public ContraMaq() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        papel = new javax.swing.JLabel();
        pedra = new javax.swing.JLabel();
        lagarto = new javax.swing.JLabel();
        spock = new javax.swing.JLabel();
        tesoura = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();

        jPanel1.setBackground(new java.awt.Color(255, 153, 153));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel3.setBackground(new java.awt.Color(0, 204, 204));
        jPanel3.setLayout(new java.awt.GridBagLayout());

        papel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iMAGES/pp1.png"))); // NOI18N
        papel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                papelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                papelMouseExited(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 57, 0, 10);
        jPanel3.add(papel, gridBagConstraints);

        pedra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iMAGES/p_1.png"))); // NOI18N
        pedra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pedraMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pedraMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pedraMouseExited(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 50, 0, 0);
        jPanel3.add(pedra, gridBagConstraints);

        lagarto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iMAGES/lg1.png"))); // NOI18N
        lagarto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lagartoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lagartoMouseExited(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 50, 47, 0);
        jPanel3.add(lagarto, gridBagConstraints);

        spock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iMAGES/sp1.png"))); // NOI18N
        spock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                spockMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                spockMouseExited(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 50, 0, 0);
        jPanel3.add(spock, gridBagConstraints);

        tesoura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iMAGES/t1.png"))); // NOI18N
        tesoura.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tesouraMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tesouraMouseExited(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 32, 0, 0);
        jPanel3.add(tesoura, gridBagConstraints);

        jPanel1.add(jPanel3, java.awt.BorderLayout.CENTER);

        jPanel5.setBackground(new java.awt.Color(0, 204, 204));
        jPanel5.setLayout(new java.awt.GridBagLayout());
        jPanel1.add(jPanel5, java.awt.BorderLayout.PAGE_END);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void pedraMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pedraMouseEntered
        // TODO add your handling code here:
        pedra.setIcon(img2);
    }//GEN-LAST:event_pedraMouseEntered

    private void pedraMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pedraMouseExited
        // TODO add your handling code here:
        pedra.setIcon(img1);
    }//GEN-LAST:event_pedraMouseExited

    private void pedraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pedraMouseClicked
        // TODO add your handling code here:
        javax.swing.JOptionPane.showMessageDialog(null,"Pedra selecionada");
        escolha =1;
    }//GEN-LAST:event_pedraMouseClicked

    private void papelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_papelMouseEntered
        // Quando o mouse entrar na area do label
        papel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iMAGES/pp2.png")));
    }//GEN-LAST:event_papelMouseEntered

    private void papelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_papelMouseExited
        // TODO add your handling code here:
        papel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iMAGES/pp1.png")));
    }//GEN-LAST:event_papelMouseExited

    private void tesouraMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tesouraMouseEntered
        // TODO add your handling code here:
        tesoura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iMAGES/t2.png")));
    }//GEN-LAST:event_tesouraMouseEntered

    private void tesouraMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tesouraMouseExited
        // TODO add your handling code here:
        tesoura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iMAGES/t1.png")));
    }//GEN-LAST:event_tesouraMouseExited

    private void spockMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_spockMouseEntered
        // TODO add your handling code here:
        spock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iMAGES/sp2.png")));
    }//GEN-LAST:event_spockMouseEntered

    private void spockMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_spockMouseExited
        // TODO add your handling code here:
        spock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iMAGES/sp1.png")));
    }//GEN-LAST:event_spockMouseExited

    private void lagartoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lagartoMouseEntered
        // TODO add your handling code here:
        lagarto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iMAGES/lg2.png")));
    }//GEN-LAST:event_lagartoMouseEntered

    private void lagartoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lagartoMouseExited
        // TODO add your handling code here:
        lagarto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iMAGES/lg1.png")));
    }//GEN-LAST:event_lagartoMouseExited
    public int escolha()
    {
        int escolhaDaMaq =(1 + random.nextInt(5));
        return escolhaDaMaq;
    }
    public int escolhaJog()
    {
        return escolha;
    }
    private int escolha=0;
    private Random random = new Random();
    private Icon img2 = new ImageIcon(getClass().getResource("/iMAGES/p_2.png"));
    private Icon img1 = new ImageIcon(getClass().getResource("/iMAGES/p_1.png"));
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel lagarto;
    private javax.swing.JLabel papel;
    private javax.swing.JLabel pedra;
    private javax.swing.JLabel spock;
    private javax.swing.JLabel tesoura;
    // End of variables declaration//GEN-END:variables
}
