/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jogoprincipal;

import java.awt.event.ItemListener;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Manoel
 */
public class TelaDeDesafio extends javax.swing.JPanel {

    /**
     * Creates new form Desafiar
     */
    public TelaDeDesafio() throws IOException {
           
        initComponents();
        
        buttonGroup1.add(escPedra);
        buttonGroup1.add(escTesoura);
        buttonGroup1.add(escPapel);
        buttonGroup1.add(escSpock);
        buttonGroup1.add(escLagarto);
         armazenarJogada = new FileWriter("Jogadas.txt");
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        titulo = new javax.swing.JLabel();
        jDesafianteJogada = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        escLagarto = new javax.swing.JRadioButton();
        escTesoura = new javax.swing.JRadioButton();
        escSpock = new javax.swing.JRadioButton();
        escPedra = new javax.swing.JRadioButton();
        escPapel = new javax.swing.JRadioButton();

        setBackground(new java.awt.Color(255, 184, 36));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        titulo.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("Desafios");

        jDesafianteJogada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDesafianteJogadaActionPerformed(evt);
            }
        });
        jDesafianteJogada.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jDesafianteJogadaKeyPressed(evt);
            }
        });

        jLabel1.setText("Quantidade de jogadas");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iMAGES/lg1.png"))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iMAGES/p_1.png"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iMAGES/pp1.png"))); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iMAGES/sp1.png"))); // NOI18N

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iMAGES/t1.png"))); // NOI18N

        escPedra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                escPedraMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jDesafianteJogada, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel2)
                        .addGap(53, 53, 53)
                        .addComponent(jLabel3)
                        .addGap(38, 38, 38)
                        .addComponent(jLabel4)
                        .addGap(28, 28, 28)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(escLagarto)
                        .addGap(143, 143, 143)
                        .addComponent(escPedra)
                        .addGap(119, 119, 119)
                        .addComponent(escPapel)
                        .addGap(103, 103, 103)
                        .addComponent(escSpock)
                        .addGap(97, 97, 97)
                        .addComponent(escTesoura)))
                .addGap(114, 114, 114))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jDesafianteJogada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(178, 178, 178)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(escLagarto)
                    .addComponent(escPedra)
                    .addComponent(escPapel)
                    .addComponent(escSpock)
                    .addComponent(escTesoura)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jDesafianteJogadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDesafianteJogadaActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jDesafianteJogadaActionPerformed

    private void jDesafianteJogadaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jDesafianteJogadaKeyPressed
        // TODO add your handling code here:
      String tecla= evt.getKeyText(evt.getKeyCode());
      if(tecla == "Enter")
      {
        try{
           quantidadeJogada = Integer.parseInt(jDesafianteJogada.getText());
           contador = quantidadeJogada;
           guardarEscolha = new String[quantidadeJogada];
           javax.swing.JOptionPane.showMessageDialog(this, jDesafianteJogada.getText());
        }catch(Exception e){
            javax.swing.JOptionPane.showMessageDialog(this,"ERRO: Entrada Invalida");
            jDesafianteJogada.setText("");
        }
         
      }
    }//GEN-LAST:event_jDesafianteJogadaKeyPressed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
        gravar(jogadas[4]);
    }//GEN-LAST:event_formMouseClicked

    private void escPedraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_escPedraMouseClicked
        // TODO add your handling code here:
        gravar(jogadas[0]);
    }//GEN-LAST:event_escPedraMouseClicked
   
    private String[] jogadas = {"PEDRA","PAPEL","TESOURA","SPOCK","LAGARTO"};
    private String[] guardarEscolha;
    private int quantidadeJogada;
    private int contador;
    FileWriter armazenarJogada;
    
    public void gravar(String jogada)
    {
        if(contador>0){
            
            try {
                BufferedWriter br = new BufferedWriter(armazenarJogada);
                br.write(jogada);
                br.newLine();
                br.close();
            } catch (IOException ex) {
                Logger.getLogger(TelaDeDesafio.class.getName()).log(Level.SEVERE, null, ex);
            }
            contador--;
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton escLagarto;
    private javax.swing.JRadioButton escPapel;
    private javax.swing.JRadioButton escPedra;
    private javax.swing.JRadioButton escSpock;
    private javax.swing.JRadioButton escTesoura;
    private javax.swing.JTextField jDesafianteJogada;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
