/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jogoprincipal;

import java.awt.event.ItemListener;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Manoel
 */
public class TelaDeDesafio extends javax.swing.JPanel {

    /**
     * Creates new form Desafiar
     */
    public TelaDeDesafio() throws IOException {
           
        initComponents();
        
        buttonGroup1.add(escPedra);
        buttonGroup1.add(escTesoura);
        buttonGroup1.add(escPapel);
        buttonGroup1.add(escSpock);
        buttonGroup1.add(escLagarto);
       
        habiDesabiOpcoes(false); 
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        buttonGroup1 = new javax.swing.ButtonGroup();
        titulo = new javax.swing.JLabel();
        jDesafianteJogada = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        escLagarto = new javax.swing.JRadioButton();
        escTesoura = new javax.swing.JRadioButton();
        escSpock = new javax.swing.JRadioButton();
        escPedra = new javax.swing.JRadioButton();
        escPapel = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 153, 0));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        setLayout(new java.awt.GridBagLayout());

        titulo.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("Desafios");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 17;
        gridBagConstraints.ipadx = 235;
        gridBagConstraints.ipady = 26;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(13, 17, 0, 0);
        add(titulo, gridBagConstraints);

        jDesafianteJogada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDesafianteJogadaActionPerformed(evt);
            }
        });
        jDesafianteJogada.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jDesafianteJogadaKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 53;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 10, 0, 0);
        add(jDesafianteJogada, gridBagConstraints);

        jLabel1.setFont(new java.awt.Font("Swis721 Lt BT", 1, 14)); // NOI18N
        jLabel1.setText("Quantidade de jogadas");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(24, 21, 0, 0);
        add(jLabel1, gridBagConstraints);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iMAGES/lg1.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(2, 10, 0, 0);
        add(jLabel2, gridBagConstraints);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iMAGES/p_1.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(2, 10, 0, 0);
        add(jLabel3, gridBagConstraints);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iMAGES/pp1.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(2, 10, 0, 0);
        add(jLabel4, gridBagConstraints);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iMAGES/sp1.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(2, 6, 0, 0);
        add(jLabel5, gridBagConstraints);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iMAGES/t1.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 18;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 19;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(2, 6, 0, 0);
        add(jLabel6, gridBagConstraints);

        escLagarto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                escLagartoMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(57, 32, 0, 0);
        add(escLagarto, gridBagConstraints);

        escTesoura.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                escTesouraMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 18;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 18;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(57, 55, 0, 0);
        add(escTesoura, gridBagConstraints);

        escSpock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                escSpockMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 16;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(57, 12, 0, 0);
        add(escSpock, gridBagConstraints);

        escPedra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                escPedraMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(57, 47, 0, 0);
        add(escPedra, gridBagConstraints);

        escPapel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                escPapelMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(57, 29, 0, 0);
        add(escPapel, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 8;
        gridBagConstraints.ipadx = 229;
        gridBagConstraints.ipady = 68;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(30, 27, 0, 0);
        add(jLabel7, gridBagConstraints);
    }// </editor-fold>                        

    private void jDesafianteJogadaActionPerformed(java.awt.event.ActionEvent evt) {                                                  
        // TODO add your handling code here:
       
    }                                                 

    private void jDesafianteJogadaKeyPressed(java.awt.event.KeyEvent evt) {                                             
        // TODO add your handling code here:
      String tecla= evt.getKeyText(evt.getKeyCode());
      if(tecla == "Enter")
      {
        try{
           //converte em inteiro a quantidade de jogadas 
           quantidadeJogada = Integer.parseInt(jDesafianteJogada.getText());
          
           
           //cria os vetores a serem guardados
           guardarEscolha = new String[quantidadeJogada];
           
           // Mostra ao usuario a quantidade escolhida
           javax.swing.JOptionPane.showMessageDialog(this, jDesafianteJogada.getText());
           
           
           habiDesabiOpcoes(true);
           jDesafianteJogada.setEnabled(false);
        }catch(Exception e){
            javax.swing.JOptionPane.showMessageDialog(this,"ERRO: Entrada Invalida");
            jDesafianteJogada.setText("");
        }
         
      }
    }                                            

    private void formMouseClicked(java.awt.event.MouseEvent evt) {                                  
       
    }                                 

    private void escPedraMouseClicked(java.awt.event.MouseEvent evt) {                                      
      try {
            gravar("PEDRA");
        } catch (IOException ex) {
            Logger.getLogger(TelaDeDesafio.class.getName()).log(Level.SEVERE, null, ex);
        }
    }                                     

    private void escLagartoMouseClicked(java.awt.event.MouseEvent evt) {                                        
        try {
            gravar("LAGARTO");
        } catch (IOException ex) {
            Logger.getLogger(TelaDeDesafio.class.getName()).log(Level.SEVERE, null, ex);
        }
    }                                       

    private void escPapelMouseClicked(java.awt.event.MouseEvent evt) {                                      
        // TODO add your handling code here:
         try {
            gravar("PAPEL");
        } catch (IOException ex) {
            Logger.getLogger(TelaDeDesafio.class.getName()).log(Level.SEVERE, null, ex);
        }
    }                                     

    private void escSpockMouseClicked(java.awt.event.MouseEvent evt) {                                      
        // TODO add your handling code here:
         try {
            gravar("SPOCK");
        } catch (IOException ex) {
            Logger.getLogger(TelaDeDesafio.class.getName()).log(Level.SEVERE, null, ex);
        }
    }                                     

    private void escTesouraMouseClicked(java.awt.event.MouseEvent evt) {                                        
        // TODO add your handling code here:
         try {
            gravar("TESOURA");
        } catch (IOException ex) {
            Logger.getLogger(TelaDeDesafio.class.getName()).log(Level.SEVERE, null, ex);
        }
    }                                       
   
   
    private String[] guardarEscolha;
    private int quantidadeJogada;
    private int contador=0;
    FileWriter armazenarJogada;
    BufferedWriter escrever;
    public void gravar(String jogada) throws IOException 
    {
        if(contador < quantidadeJogada)
        {
            guardarEscolha[contador] = jogada;
            contador++;
            jLabel7.setText(String.format("%dº jogada",contador));
        }else
        {
            habiDesabiOpcoes(false);
            int salvar =javax.swing.JOptionPane.showConfirmDialog(this,"Salvar?","Deseja salvar as jogadas",JOptionPane.YES_NO_OPTION);
            if(salvar==JOptionPane.YES_OPTION){
                salvarEmTxt();
                javax.swing.JOptionPane.showMessageDialog(this,"Informações salvas\n Aperte em Menu para voltar"
                        ,"Confirmação", JOptionPane.INFORMATION_MESSAGE);
                setBackground(new java.awt.Color(102,102,102));
                
            }else{
                contador = 0;
                guardarEscolha = null;
            }    
        }
        
    }//fim de gravar
    
    public void habiDesabiOpcoes(boolean pode)
    {
        escSpock.setEnabled(pode);
        escLagarto.setEnabled(pode);
        escTesoura.setEnabled(pode);
        escPapel.setEnabled(pode);
        escPedra.setEnabled(pode);
        
    }
    
    //grava no arquivo txt as 
    public void salvarEmTxt() throws IOException
    {
        for(int i = 0; i <quantidadeJogada;i++)
        {
            armazenarJogada = new FileWriter("Jogadas.txt",true);
            escrever = new BufferedWriter(armazenarJogada);
                escrever.write(Crip(guardarEscolha[i],1));
                escrever.newLine();
            escrever.close();
            armazenarJogada.close();
        }
    }
    public static String Crip(String mensagem, int chave){
        StringBuilder builder = new StringBuilder();
 
        for (int i = 0; i < mensagem.length(); i++) {
            char c = (char)(mensagem.charAt(i) + chave);
            builder.append(c);
        }
 
        return builder.toString();
    }
    
    // Variables declaration - do not modify                     
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton escLagarto;
    private javax.swing.JRadioButton escPapel;
    private javax.swing.JRadioButton escPedra;
    private javax.swing.JRadioButton escSpock;
    private javax.swing.JRadioButton escTesoura;
    private javax.swing.JTextField jDesafianteJogada;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel titulo;
    // End of variables declaration                   
}
